### PR TITLE
Debian/unstable

### PR DESCRIPTION
**Pull request by borenius-dfn-de**
My latest minor corrections to the debian packaging. The github diff is showing the changes to the debian/jessie branch, but these should of course go into the debian/unstable branch. Am I doing something wrong?

### CODE REVIEW

**Comment by laeti-tia** [comment]
Hi Raoul.  I think this is because the pull request is made with the old reference to our repo.  I think that if you pull the changes from the remote repo (this repo) first, you can then do a updated PR that will look better (i.e. without the first 4 commits that are already merged).

**Comment by vvidic** [comment]
What should we do about these Debian unstable packages?

**Comment by laeti-tia** [comment]
> What should we do about these Debian unstable packages?

We will not publish the perfSONAR packages to the official Debian repositories, our software is evolving to quickly and we don't want to have people running 2 years old perfSONAR versions.  So the debian/unstable branch will not be used anymore.

That being said, I think we should still review the proposed patches to see if they are still relevant and bring back those changes into the main branches if it's the case.

**Comment by borenius-dfn-de** [comment]
Hello Antoine,

On Thu, Feb 28, 2019 at 08:34:52AM -0800, Antoine Delvaux wrote:
>     What should we do about these Debian unstable packages?
> 
> We will not publish the perfSONAR packages to the official Debian repositories,
> our software is evolving to quickly and we don't want to have people running 2
> years old perfSONAR versions. So the debian/unstable branch will not be used
> anymore.

Yes, I can understand that. I'm going to remove my packages from the Debian
repository.

> That being said, I think we should still review the proposed patches to see if
> they are still relevant and bring back those changes into the main branches if
> it's the case.

That would be good of course. There were just a few small patches if
I remember correctly.

Congrats to your work on the creating the Perfsonar Debian packages!
Really great work! It helps us a lot, we are using them on our
Personar installations and it all works very well!

Great job!

 Best regards,

  Raoul

-- 
---------------------------------------------------------------------
Raoul Gunnar Borenius                  Phone  : +49 711 63314-206
DFN-Verein, Geschäftsstelle Stuttgart  Fax    : +49 711 63314-133
Lindenspürstr.32                       E-Mail : borenius@dfn.de
D-70176 Stuttgart                      WWW    : http://www.dfn.de
---------------------------------------------------------------------
--------------------- Deutsches Forschungsnetz ----------------------
--------- Germany's National Research and Education Network ---------
---------------------------------------------------------------------

**Pull request merged**
